language: crystal
services: docker

before_install:
  - docker run -p 2379:2379 -p 2380:2380 -e ALLOW_NONE_AUTHENTICATION=yes -d bitnami/etcd:3.4.15

install:
  - shards install --ignore-crystal-version

before_script:
  - sleep 5

script:
  - crystal spec -v
  - crystal tool format --check
  - bin/ameba
