language: crystal

services:
  - docker

before_install:
  # Install ETCD
  - docker run -p "2379:2379" -p "2380:2380" -e ALLOW_NONE_AUTHENTICATION=yes -d bitnami/etcd:3.3.13
  - sleep 5
  - export TRAVIS_TEST=true

install:
  - shards install

before_script:
  - sleep 5

script:
  - crystal spec
  - crystal tool format --check
  - bin/ameba
